In [1]:
#encoding=utf-8
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

# get tfidf

In [2]:
path = '/home/kai/data/jiangning/Chatbot_1/Chatbot1.0/data/'
data = pd.read_csv(path + 'cleaned_mock_up_data.csv', encoding='utf8')
print(data.shape)
data.head(10)

(186, 2)


split_text  label
0                                              ['啊']      1
1  ['你', '有病', '吧', '我', '跟你', '说过', '很多次', '了', ...      2
2                                      ['不是', '什么事']      2
3                                         ['啊', '对']      1
4                                              ['对']      1
5                                              ['对']      1
6                                   ['我', '不是', '啊']      2
7                                              ['噢']      1
8                                              ['啊']      1
9                                              ['啊']      1

In [3]:
# phrase_vectorizer1 = TfidfVectorizer(ngram_range=(1,3),
#                                     strip_accents='unicode', 
#                                     max_features=100000, 
#                                     analyzer='word',
#                                     sublinear_tf=True,
#                                     token_pattern=r'\w{1,}')
# data.split_text.iloc[:2]
# dd = ['I like apple do you like it', 'I do not like banana']
# phrase_vectorizer1.fit(dd)

# print('transform phrase')
# phrase = phrase_vectorizer1.transform(dd)


In [4]:
data.split_text.iloc[1]

"['你', '有病', '吧', '我', '跟你', '说过', '很多次', '了', '我', '不是', '他']"

In [6]:
# phrase_vectorizer1.vocabulary_

In [7]:
phrase_vectorizer = TfidfVectorizer(ngram_range=(1,3),
                                    strip_accents='unicode', 
                                    max_features=100000, 
                                    analyzer='word',
                                    sublinear_tf=True,
                                    token_pattern=r'\w{1,}')

print('fitting phrase')
phrase_vectorizer.fit(data.split_text)

print('transform phrase')
phrase = phrase_vectorizer.transform(data.split_text)

phrase

fitting phrase
transform phrase


<186x896 sparse matrix of type '<class 'numpy.float64'>'
	with 1515 stored elements in Compressed Sparse Row format>

# SVC

In [8]:
from sklearn.svm import LinearSVC

In [9]:
l_svc = LinearSVC()
l_svc.fit(phrase, data.label)
print(l_svc.score(phrase, data.label))

1.0


In [10]:
print(l_svc.predict(phrase))

[1 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 1 3 3 3 3 3 3
 3 1 1 1 1 3 3 3 1 2 2 3 3 2 1 1 3 3 3 3 2 2 2 3 1 1 2 1 1 1 1 1 1 1 2 3 2
 1 1 3 3 1 1 1 2 1 1 1 1 2 1 2 1 2 2 3 3 2 1 3 2 3 3 2 2 2 1 3 2 1 1 1 2 2
 1 1 1 2 3 3 1 3 3 2 1 1 2 3 1 3 2 1 1 2 2 2 1 1 2 1 1 1 1 1 1 1 1 1 2 2 1
 1]


# logistic

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
log_r = LogisticRegression()
log_r.fit(phrase, data.label)
print(log_r.score(phrase, data.label))

0.811827956989


In [26]:
print(log_r.predict(phrase))

[1 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 3 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 1 1 2 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 2 1 2
 1 1 3 1 1 1 1 2 1 1 1 1 2 1 2 1 1 2 1 1 2 1 1 2 1 1 1 2 2 1 1 2 1 1 1 2 2
 1 1 1 2 1 1 1 1 3 2 1 1 2 3 1 1 1 1 1 2 1 2 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1
 1]


In [27]:
# l_svc.predict(phrase)-log_r.predict(phrase)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2,
       2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2,
       2, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 2, 2, 1,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0])

# lightGBM

In [14]:
import lightgbm as lgb

In [15]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data.label.values)
onelabels = le.transform(data.label.values)

In [16]:
onelabels

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0])

In [17]:
from sklearn.preprocessing import MultiLabelBinarizer
multicoder = MultiLabelBinarizer()
lables = multicoder.fit_transform([data.label.values])

In [18]:
lables

array([[1, 1, 1]])

In [19]:
data.label.values

array([1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 3,
       3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 3, 3, 3, 1, 2, 2, 3, 3, 2, 1, 1, 3, 3,
       3, 3, 2, 2, 2, 3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 3, 2, 1, 1, 3, 3,
       1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 3, 3, 2, 1, 3, 2, 3, 3, 2,
       2, 2, 1, 3, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 3, 3, 1, 3, 3, 2, 1, 1, 2,
       3, 1, 3, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1])

In [20]:
lables.todense()

AttributeError: 'numpy.ndarray' object has no attribute 'todense'

In [23]:
params = {
    'learning_rate': 0.2,
    'num_iterations':1000,
    'application': 'multiclassova',
    'num_class': 3,
    'num_leaves': 31,
    'verbosity': -1,
    'metric': 'multi_error',
    'data_random_seed': 2,
#     'bagging_fraction': 0.8,
#     'feature_fraction': 0.6,
    'nthread': 4,
    'lambda_l1': 1,
    'lambda_l2': 1,
    'early_stopping_round':200
} 

# lgbm_train = lgb.Dataset(phrase, data.label)
lgbm_train = lgb.Dataset(phrase, onelabels)
lgbm_val = lgb.Dataset(phrase, onelabels)
lgbm_model = lgb.train(params,lgbm_train,valid_sets=lgbm_val, verbose_eval=5)

/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:99: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:104: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


Training until validation scores don't improve for 200 rounds.
[5]	valid_0's multi_error: 0.231183
[10]	valid_0's multi_error: 0.193548
[15]	valid_0's multi_error: 0.193548
[20]	valid_0's multi_error: 0.198925
[25]	valid_0's multi_error: 0.198925
[30]	valid_0's multi_error: 0.198925
[35]	valid_0's multi_error: 0.193548
[40]	valid_0's multi_error: 0.193548
[45]	valid_0's multi_error: 0.193548
[50]	valid_0's multi_error: 0.193548
[55]	valid_0's multi_error: 0.193548
[60]	valid_0's multi_error: 0.193548
[65]	valid_0's multi_error: 0.193548
[70]	valid_0's multi_error: 0.193548
[75]	valid_0's multi_error: 0.193548
[80]	valid_0's multi_error: 0.193548
[85]	valid_0's multi_error: 0.193548
[90]	valid_0's multi_error: 0.193548
[95]	valid_0's multi_error: 0.188172
[100]	valid_0's multi_error: 0.188172
[105]	valid_0's multi_error: 0.188172
[110]	valid_0's multi_error: 0.188172
[115]	valid_0's multi_error: 0.188172
[120]	valid_0's multi_error: 0.188172
[125]	valid_0's multi_error: 0.188172
[130]	v

In [24]:
print(lgbm_model.predict(phrase))

[[ 0.88585207  0.03239564  0.09572226]
 [ 0.00893941  0.85434015  0.02105471]
 [ 0.06960235  0.91307727  0.03298403]
 [ 0.97521996  0.03239564  0.02398933]
 [ 0.93548932  0.05046976  0.05631173]
 [ 0.93548932  0.05046976  0.05631173]
 [ 0.08006884  0.89999954  0.00896208]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.88585207  0.03239564  0.09572226]
 [ 0.88585207  0.03239564  0.09572226]
 [ 0.97521996  0.03239564  0.02398933]
 [ 0.95538356  0.02038456  0.06165284]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.97521996  0.03239564  0.02398933]
 [ 0.97521996  0.03239564  0.02398933]
 [ 0.93548932  0.05046976  0.05631173]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.88585207  0.03239564  0.09572226]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.95538356  0.02038456  0.06165284]
 [ 0.95538356  0.02038456  0.06165284]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.88585207  0.03239564  0.09572226]
 [ 0.73692761  0.05046976  0.21793354]
 [ 0.73692761  0.05046976

In [ ]:
lgbm_model.predict(phrase)

In [135]:
phrase

<186x896 sparse matrix of type '<class 'numpy.float64'>'
	with 1515 stored elements in Compressed Sparse Row format>

# SAVE

In [136]:
import pickle

pickle.dump(phrase_vectorizer, open("tfidf.pickle", "wb"))
# pickle.dump(train_comment_features, open("train_comment_features.pickle", "wb"))
# pickle.dump(test_comment_features, open("test_comment_features.pickle", "wb"))

In [143]:
aa = pickle.load(open("tfidf.pickle", 'rb'))

In [171]:
bb = phrase_vectorizer.transform(['是'])

In [172]:
bb

<1x896 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [173]:
lgbm_model.predict(bb)

array([[ 0.78397288,  0.05191403,  0.16411309]])

In [174]:
lgbm_model.best_iteration

0

In [189]:
import numpy as np
from sklearn.metrics import roc_auc_score
y_true = np.array([0, 0, 1, 2,])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
roc_auc_score(y_true, y_scores)

ValueError: multiclass format is not supported