In [1]:
#encoding=utf-8
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

# get tfidf

In [2]:
# path = '/home/kai/data/jiangning/Chatbot_1/Chatbot1.0/data/'
path = '../../data/IDClassifier/'
data = pd.read_csv(path + 'cleaned_mock_up_data.csv', encoding='utf8')
print(data.shape)
data.head(10)

(315, 2)


split_text  label
0                            啊      0
1  你 有病 吧 我 跟你 说过 很多次 了 我 不是 他      1
2                       不是 什么事      1
3                          啊 对      0
4                            对      0
5                            对      0
6                       我 不是 啊      1
7                            噢      0
8                            啊      0
9                            啊      0

In [3]:
# phrase_vectorizer1 = TfidfVectorizer(ngram_range=(1,3),
#                                     strip_accents='unicode', 
#                                     max_features=100000, 
#                                     analyzer='word',
#                                     sublinear_tf=True,
#                                     token_pattern=r'\w{1,}')
# data.split_text.iloc[:2]
# dd = ['I like apple do you like it', 'I do not like banana']
# phrase_vectorizer1.fit(dd)

# print('transform phrase')
# phrase = phrase_vectorizer1.transform(dd)


In [4]:
data.split_text.iloc[1]

'你 有病 吧 我 跟你 说过 很多次 了 我 不是 他'

In [5]:
# phrase_vectorizer1.vocabulary_

In [6]:
phrase_vectorizer = TfidfVectorizer(ngram_range=(1,3),
                                    strip_accents='unicode', 
                                    max_features=100000, 
                                    analyzer='word',
                                    sublinear_tf=True,
                                    token_pattern=r'\w{1,}')

print('fitting phrase')
phrase_vectorizer.fit(data.split_text)

print('transform phrase')
phrase = phrase_vectorizer.transform(data.split_text)

phrase

fitting phrase
transform phrase


<315x1616 sparse matrix of type '<class 'numpy.float64'>'
	with 3161 stored elements in Compressed Sparse Row format>

# SVC

In [7]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC

l_svc = LinearSVC()
clf = CalibratedClassifierCV(l_svc) 
clf.fit(phrase, data.label)
print(clf.score(phrase, data.label))

0.996825396825


In [8]:
print(clf.predict(phrase))

[0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 2 2 1 2 2 2
 2 0 0 0 0 2 2 2 0 1 1 2 2 1 0 0 2 2 2 2 1 1 1 2 0 0 1 0 0 0 0 0 0 0 1 2 1
 0 0 2 2 0 0 0 1 0 0 0 0 1 0 1 0 1 1 2 2 1 0 2 1 2 2 1 1 1 0 2 1 0 0 0 1 1
 0 0 0 1 2 2 0 2 2 1 0 0 1 2 0 2 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 2 2 2 2 2 2 2 1 1 1 1 0 1 1 1 1
 1 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1 2 2]


In [9]:
# import pickle
# pickle.dump(clf, open("../../savedModel/IDClassifier/l_svc.pickle", "wb"))

In [10]:
# aa = pickle.load(open("../../savedModel/IDClassifier/l_svc.pickle", 'rb'))

In [11]:
# aa.predict(phrase)

# logistic

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
log_r = LogisticRegression()
log_r.fit(phrase, data.label)
print(log_r.score(phrase, data.label))

0.869841269841


In [14]:
print(log_r.predict(phrase))

[0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 2 0 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 2 2 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1
 0 0 2 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1
 0 0 0 1 2 2 0 0 1 1 0 0 1 2 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 2 2 0 0 2 2 2 2 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0 2 0]


In [15]:
# l_svc.predict(phrase)-log_r.predict(phrase)

# lightGBM

In [16]:
import lightgbm as lgb

In [17]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data.label.values)
onelabels = le.transform(data.label.values)

In [18]:
onelabels

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0,

In [19]:
from sklearn.preprocessing import MultiLabelBinarizer
multicoder = MultiLabelBinarizer()
lables = multicoder.fit_transform([data.label.values])

In [20]:
lables

array([[1, 1, 1]])

In [21]:
data.label.values

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0,

In [22]:
# lables.todense()

In [23]:
params = {
    'learning_rate': 0.2,
    'num_iterations':1000,
    'application': 'multiclassova',
    'num_class': 3,
    'num_leaves': 31,
    'verbosity': -1,
    'metric': 'multi_error',
    'data_random_seed': 2,
#     'bagging_fraction': 0.8,
#     'feature_fraction': 0.6,
    'nthread': 4,
    'lambda_l1': 1,
    'lambda_l2': 1,
    'early_stopping_round':200
} 

# lgbm_train = lgb.Dataset(phrase, data.label)
lgbm_train = lgb.Dataset(phrase, onelabels)
lgbm_val = lgb.Dataset(phrase, onelabels)
lgbm_model = lgb.train(params,lgbm_train,valid_sets=lgbm_val, verbose_eval=5)

Training until validation scores don't improve for 200 rounds.
[5]	valid_0's multi_error: 0.2
[10]	valid_0's multi_error: 0.184127
[15]	valid_0's multi_error: 0.184127
[20]	valid_0's multi_error: 0.180952
[25]	valid_0's multi_error: 0.174603
[30]	valid_0's multi_error: 0.168254
[35]	valid_0's multi_error: 0.161905
[40]	valid_0's multi_error: 0.146032
[45]	valid_0's multi_error: 0.149206
[50]	valid_0's multi_error: 0.146032
[55]	valid_0's multi_error: 0.146032
[60]	valid_0's multi_error: 0.142857
[65]	valid_0's multi_error: 0.139683
[70]	valid_0's multi_error: 0.139683
[75]	valid_0's multi_error: 0.139683
[80]	valid_0's multi_error: 0.139683
[85]	valid_0's multi_error: 0.139683
[90]	valid_0's multi_error: 0.139683
[95]	valid_0's multi_error: 0.139683
[100]	valid_0's multi_error: 0.139683
[105]	valid_0's multi_error: 0.139683
[110]	valid_0's multi_error: 0.139683
[115]	valid_0's multi_error: 0.139683
[120]	valid_0's multi_error: 0.139683
[125]	valid_0's multi_error: 0.139683
[130]	valid_

/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:99: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:104: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


In [24]:
print(lgbm_model.predict(phrase))

[[ 0.94323645  0.02557927  0.06746674]
 [ 0.01498715  0.98644267  0.01062963]
 [ 0.02003398  0.93772088  0.06632066]
 [ 0.98267571  0.01983274  0.01414456]
 [ 0.97051283  0.024572    0.0192952 ]
 [ 0.97051283  0.024572    0.0192952 ]
 [ 0.07237949  0.96449463  0.00830726]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.94323645  0.02557927  0.06746674]
 [ 0.94323645  0.02557927  0.06746674]
 [ 0.98267571  0.01983274  0.01414456]
 [ 0.9871481   0.01316497  0.0182827 ]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.98267571  0.01983274  0.01414456]
 [ 0.98267571  0.01983274  0.01414456]
 [ 0.97051283  0.024572    0.0192952 ]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.94323645  0.02557927  0.06746674]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.9871481   0.01316497  0.0182827 ]
 [ 0.9871481   0.01316497  0.0182827 ]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.94323645  0.02557927  0.06746674]
 [ 0.68927464  0.05554296  0.23413488]
 [ 0.68927464  0.05554296

In [25]:
# lgbm_model.predict(phrase)

In [26]:
phrase

<315x1616 sparse matrix of type '<class 'numpy.float64'>'
	with 3161 stored elements in Compressed Sparse Row format>

# Save

In [27]:
import pickle

# save tfidf
pickle.dump(phrase_vectorizer, open("../../savedModel/IDClassifier/tfidf.pickle", "wb"))
# pickle.dump(train_comment_features, open("train_comment_features.pickle", "wb"))
# pickle.dump(test_comment_features, open("test_comment_features.pickle", "wb"))

# save linear svc
pickle.dump(clf, open("../../savedModel/IDClassifier/LinearSVC.pickle", "wb"))
# save logistic
pickle.dump(log_r, open("../../savedModel/IDClassifier/Logistic.pickle", "wb"))
# save lightGBM
pickle.dump(lgbm_model, open("../../savedModel/IDClassifier/Lgbm.pickle", "wb"))

In [29]:
pickle.load(open("../../savedModel/IDClassifier/Lgbm.pickle", 'rb'))

In [30]:
# test = phrase_vectorizer.transform(['你 说 呢'])
test = phrase_vectorizer.transform(['我 在 洗澡'])


In [31]:
test

<1x1616 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [32]:
clf.predict_proba(test) # linear svc

array([[ 0.74072542,  0.19775083,  0.06152376]])

In [33]:
log_r.predict_proba(test) # logistic

array([[ 0.55555328,  0.309785  ,  0.13466172]])

In [34]:
lgbm_model.predict(test) # light gbm

array([[ 0.91661729,  0.06467584,  0.03067064]])

# labeling

In [35]:
# basic logic: find the max probability of 3 models, if it is larger than threshold, return the corresponding label, otherwise, return 2 (others).
result = np.vstack((clf.predict_proba(test),log_r.predict_proba(test),lgbm_model.predict(test)))
pos = np.where(result == np.max(result))

threshold = 0.7
if np.max(result)<threshold:
    label = 2
else:
    label = pos[1]
    label = label[0]
    
print('label=',label)
print('prob=',np.max(result))

label= 0
prob= 0.916617290186
