In [13]:
#encoding=utf-8
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

# get tfidf

In [14]:
# path = '/home/kai/data/jiangning/Chatbot_1/Chatbot1.0/data/'
path = '../../data/IDClassifier/'
data = pd.read_csv(path + 'cleaned_mock_up_data.csv', encoding='utf8')
print(data.shape)
data.head(10)

(213, 2)


split_text  label
0                            啊      0
1  你 有病 吧 我 跟你 说过 很多次 了 我 不是 他      1
2                       不是 什么事      1
3                          啊 对      0
4                            对      0
5                            对      0
6                       我 不是 啊      1
7                            噢      0
8                            啊      0
9                            啊      0

In [15]:
# phrase_vectorizer1 = TfidfVectorizer(ngram_range=(1,3),
#                                     strip_accents='unicode', 
#                                     max_features=100000, 
#                                     analyzer='word',
#                                     sublinear_tf=True,
#                                     token_pattern=r'\w{1,}')
# data.split_text.iloc[:2]
# dd = ['I like apple do you like it', 'I do not like banana']
# phrase_vectorizer1.fit(dd)

# print('transform phrase')
# phrase = phrase_vectorizer1.transform(dd)


In [16]:
data.split_text.iloc[1]

'你 有病 吧 我 跟你 说过 很多次 了 我 不是 他'

In [17]:
# phrase_vectorizer1.vocabulary_

In [18]:
phrase_vectorizer = TfidfVectorizer(ngram_range=(1,3),
                                    strip_accents='unicode', 
                                    max_features=100000, 
                                    analyzer='word',
                                    sublinear_tf=True,
                                    token_pattern=r'\w{1,}')

print('fitting phrase')
phrase_vectorizer.fit(data.split_text)

print('transform phrase')
phrase = phrase_vectorizer.transform(data.split_text)

phrase

fitting phrase
transform phrase


<213x955 sparse matrix of type '<class 'numpy.float64'>'
	with 1658 stored elements in Compressed Sparse Row format>

# SVC

In [19]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC

l_svc = LinearSVC()
clf = CalibratedClassifierCV(l_svc) 
clf.fit(phrase, data.label)
print(clf.score(phrase, data.label))

1.0


In [20]:
print(clf.predict(phrase))

[0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 2 2 2 2 2 2
 2 0 0 0 0 2 2 2 0 1 1 2 2 1 0 0 2 2 2 2 1 1 1 2 0 0 1 0 0 0 0 0 0 0 1 2 1
 0 0 2 2 0 0 0 1 0 0 0 0 1 0 1 0 1 1 2 2 1 0 2 1 2 2 1 1 1 0 2 1 0 0 0 1 1
 0 0 0 1 2 2 0 2 2 1 0 0 1 2 0 2 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1]


In [24]:
import pickle
pickle.dump(clf, open("../../savedModel/IDClassifier/l_svc.pickle", "wb"))

In [25]:
aa = pickle.load(open("../../savedModel/IDClassifier/l_svc.pickle", 'rb'))

In [26]:
aa.predict(phrase)

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1])

# logistic

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
log_r = LogisticRegression()
log_r.fit(phrase, data.label)
print(log_r.score(phrase, data.label))

0.830985915493


In [15]:
print(log_r.predict(phrase))

[0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 2 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 1
 0 0 2 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1
 0 0 0 1 0 0 0 0 2 1 0 0 1 2 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 0 0 1 0 1 1 1 1 1 1 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0]


In [16]:
# l_svc.predict(phrase)-log_r.predict(phrase)

# lightGBM

In [17]:
import lightgbm as lgb

In [18]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data.label.values)
onelabels = le.transform(data.label.values)

In [19]:
onelabels

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1])

In [20]:
from sklearn.preprocessing import MultiLabelBinarizer
multicoder = MultiLabelBinarizer()
lables = multicoder.fit_transform([data.label.values])

In [21]:
lables

array([[1, 1, 1]])

In [22]:
data.label.values

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 2, 2,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1,
       2, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1])

In [23]:
# lables.todense()

In [24]:
params = {
    'learning_rate': 0.2,
    'num_iterations':1000,
    'application': 'multiclassova',
    'num_class': 3,
    'num_leaves': 31,
    'verbosity': -1,
    'metric': 'multi_error',
    'data_random_seed': 2,
#     'bagging_fraction': 0.8,
#     'feature_fraction': 0.6,
    'nthread': 4,
    'lambda_l1': 1,
    'lambda_l2': 1,
    'early_stopping_round':200
} 

# lgbm_train = lgb.Dataset(phrase, data.label)
lgbm_train = lgb.Dataset(phrase, onelabels)
lgbm_val = lgb.Dataset(phrase, onelabels)
lgbm_model = lgb.train(params,lgbm_train,valid_sets=lgbm_val, verbose_eval=5)

Training until validation scores don't improve for 200 rounds.
[5]	valid_0's multi_error: 0.262911
[10]	valid_0's multi_error: 0.262911
[15]	valid_0's multi_error: 0.258216
[20]	valid_0's multi_error: 0.262911
[25]	valid_0's multi_error: 0.253521
[30]	valid_0's multi_error: 0.258216
[35]	valid_0's multi_error: 0.258216
[40]	valid_0's multi_error: 0.253521
[45]	valid_0's multi_error: 0.244131
[50]	valid_0's multi_error: 0.239437
[55]	valid_0's multi_error: 0.239437
[60]	valid_0's multi_error: 0.244131
[65]	valid_0's multi_error: 0.244131
[70]	valid_0's multi_error: 0.239437
[75]	valid_0's multi_error: 0.239437
[80]	valid_0's multi_error: 0.239437
[85]	valid_0's multi_error: 0.239437
[90]	valid_0's multi_error: 0.239437
[95]	valid_0's multi_error: 0.239437
[100]	valid_0's multi_error: 0.239437
[105]	valid_0's multi_error: 0.239437
[110]	valid_0's multi_error: 0.239437
[115]	valid_0's multi_error: 0.239437
[120]	valid_0's multi_error: 0.239437
[125]	valid_0's multi_error: 0.239437
[130]	v

/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:99: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:104: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


In [25]:
print(lgbm_model.predict(phrase))

[[ 0.93232931  0.0285261   0.04805912]
 [ 0.03088033  0.90672612  0.01328779]
 [ 0.02683796  0.96635572  0.02975403]
 [ 0.98054547  0.02170001  0.02226349]
 [ 0.94929452  0.05904896  0.05583565]
 [ 0.94929452  0.05904896  0.05583565]
 [ 0.04523034  0.91816321  0.0041229 ]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.93232931  0.0285261   0.04805912]
 [ 0.93232931  0.0285261   0.04805912]
 [ 0.98054547  0.02170001  0.02226349]
 [ 0.96644191  0.01912252  0.06107039]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.98054547  0.02170001  0.02226349]
 [ 0.98054547  0.02170001  0.02226349]
 [ 0.94929452  0.05904896  0.05583565]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.93232931  0.0285261   0.04805912]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.96644191  0.01912252  0.06107039]
 [ 0.96644191  0.01912252  0.06107039]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.93232931  0.0285261   0.04805912]
 [ 0.69170097  0.08231551  0.19248124]
 [ 0.69170097  0.08231551

In [26]:
# lgbm_model.predict(phrase)

In [27]:
phrase

<187x897 sparse matrix of type '<class 'numpy.float64'>'
	with 1518 stored elements in Compressed Sparse Row format>

# Save

In [22]:
import pickle

pickle.dump(phrase_vectorizer, open("../../savedModel/IDClassifier/tfidf.pickle", "wb"))
# pickle.dump(train_comment_features, open("train_comment_features.pickle", "wb"))
# pickle.dump(test_comment_features, open("test_comment_features.pickle", "wb"))

In [23]:
pickle.load(open("../../savedModel/IDClassifier/tfidf.pickle", 'rb'))

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=100000, min_df=1,
        ngram_range=(1, 3), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents='unicode', sublinear_tf=True,
        token_pattern='\\w{1,}', tokenizer=None, use_idf=True,
        vocabulary=None)

In [33]:
test = phrase_vectorizer.transform(['是'])

In [34]:
test

<1x897 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [35]:
lgbm_model.predict(test)

array([[ 0.71390415,  0.1293083 ,  0.20135782]])