In [1]:
#encoding=utf-8
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

In [2]:
# path = '/home/kai/data/jiangning/Chatbot_1/Chatbot1.0/data/'
path = '../../data/CutDebt/'
data = pd.read_csv(path + 'cleaned_mock_up_data.csv', encoding='utf8')
print(data.shape)
data.head(10)

(3205, 2)


label                  split_text
0      2                         我 吃
1      1      我 接受 救济   但 我 仍然 负担 不起
2      2                   显然 你 错过 了
3      0                          伟大
4      1  原来   利息 较 少   主要 金额 低得 多 。
5      0                       那 太好了
6      0                        那么 帅
7      1                          没有
8      2                      我 不 知道
9      0                          很棒

In [3]:
data.split_text.iloc[89]

'我 可以 备份 我 的 校长 吗 ？'

In [4]:
phrase_vectorizer = TfidfVectorizer(ngram_range=(1,3),
                                    strip_accents='unicode', 
                                    max_features=100000, 
                                    analyzer='word',
                                    sublinear_tf=True,
                                    token_pattern=r'\w{1,}')

print('fitting phrase')
phrase_vectorizer.fit(data.split_text)

print('transform phrase')
phrase = phrase_vectorizer.transform(data.split_text)

phrase

fitting phrase
transform phrase


<3205x7971 sparse matrix of type '<class 'numpy.float64'>'
	with 26922 stored elements in Compressed Sparse Row format>

# SVC

In [5]:
from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC

l_svc = LinearSVC()
clf = CalibratedClassifierCV(l_svc) 
clf.fit(phrase, data.label)
print(clf.score(phrase, data.label))

0.990951638066


In [6]:
print(clf.predict(phrase))

[2 1 2 ..., 0 2 1]


# Logistic

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
log_r = LogisticRegression()
log_r.fit(phrase, data.label)
print(log_r.score(phrase, data.label))

0.973478939158


In [9]:
print(log_r.predict(phrase))

[2 1 2 ..., 0 2 1]


# LightGBM

In [10]:
import lightgbm as lgb

In [11]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(data.label.values)
onelabels = le.transform(data.label.values)

In [12]:
onelabels

array([2, 1, 2, ..., 0, 2, 1])

In [13]:
from sklearn.preprocessing import MultiLabelBinarizer
multicoder = MultiLabelBinarizer()
lables = multicoder.fit_transform([data.label.values])

In [14]:
lables

array([[1, 1, 1]])

In [15]:
data.label.values

array([2, 1, 2, ..., 0, 2, 1])

In [16]:
params = {
    'learning_rate': 0.2,
    'num_iterations':1000,
    'application': 'multiclassova',
    'num_class': 3,
    'num_leaves': 31,
    'verbosity': -1,
    'metric': 'multi_error',
    'data_random_seed': 2,
#     'bagging_fraction': 0.8,
#     'feature_fraction': 0.6,
    'nthread': 4,
    'lambda_l1': 1,
    'lambda_l2': 1,
    'early_stopping_round':200
} 

# lgbm_train = lgb.Dataset(phrase, data.label)
lgbm_train = lgb.Dataset(phrase, onelabels)
lgbm_val = lgb.Dataset(phrase, onelabels)
lgbm_model = lgb.train(params,lgbm_train,valid_sets=lgbm_val, verbose_eval=5)

/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:99: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/home/kai/anaconda3/lib/python3.6/site-packages/lightgbm/engine.py:104: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))


Training until validation scores don't improve for 200 rounds.
[5]	valid_0's multi_error: 0.219657
[10]	valid_0's multi_error: 0.200312
[15]	valid_0's multi_error: 0.180655
[20]	valid_0's multi_error: 0.165679
[25]	valid_0's multi_error: 0.15663
[30]	valid_0's multi_error: 0.144462
[35]	valid_0's multi_error: 0.136661
[40]	valid_0's multi_error: 0.132605
[45]	valid_0's multi_error: 0.126989
[50]	valid_0's multi_error: 0.124493
[55]	valid_0's multi_error: 0.121061
[60]	valid_0's multi_error: 0.117005
[65]	valid_0's multi_error: 0.114509
[70]	valid_0's multi_error: 0.1117
[75]	valid_0's multi_error: 0.111076
[80]	valid_0's multi_error: 0.109204
[85]	valid_0's multi_error: 0.10858
[90]	valid_0's multi_error: 0.107644
[95]	valid_0's multi_error: 0.107332
[100]	valid_0's multi_error: 0.106708
[105]	valid_0's multi_error: 0.10546
[110]	valid_0's multi_error: 0.10546
[115]	valid_0's multi_error: 0.104836
[120]	valid_0's multi_error: 0.1039
[125]	valid_0's multi_error: 0.102964
[130]	valid_0's

In [17]:
print(lgbm_model.predict(phrase))

[[ 0.11967434  0.25307     0.57791042]
 [ 0.01836455  0.99789293  0.00131995]
 [ 0.01974777  0.12126563  0.9138999 ]
 ..., 
 [ 0.3867389   0.20953583  0.34748087]
 [ 0.04886143  0.26983066  0.642391  ]
 [ 0.00233076  0.99778701  0.00251698]]


# Save

In [18]:
import pickle

# save tfidf
pickle.dump(phrase_vectorizer, open("../../savedModel/CutDebt/tfidf.pickle", "wb"))
# pickle.dump(train_comment_features, open("train_comment_features.pickle", "wb"))
# pickle.dump(test_comment_features, open("test_comment_features.pickle", "wb"))

# save linear svc
pickle.dump(clf, open("../../savedModel/CutDebt/LinearSVC.pickle", "wb"))
# save logistic
pickle.dump(log_r, open("../../savedModel/CutDebt/Logistic.pickle", "wb"))
# save lightGBM
pickle.dump(lgbm_model, open("../../savedModel/CutDebt/Lgbm.pickle", "wb"))

In [19]:
test = phrase_vectorizer.transform(['真的 没 那么 多'])
# test = phrase_vectorizer.transform(['我 在 洗澡'])


In [20]:
clf.predict_proba(test) # linear svc

array([[ 0.02700852,  0.96551342,  0.00747806]])

In [21]:
log_r.predict_proba(test) # logistic

array([[ 0.13666924,  0.79194295,  0.07138781]])

In [22]:
lgbm_model.predict(test) # light gbm

array([[ 0.00638464,  0.98398606,  0.00755999]])

# Labeling

In [23]:
# basic logic: find the max probability of 3 models, if it is larger than threshold, return the corresponding label, otherwise, return 2 (others).
result = np.vstack((clf.predict_proba(test),log_r.predict_proba(test),lgbm_model.predict(test)))
pos = np.where(result == np.max(result))

threshold = 0.7
if np.max(result)<threshold:
    label = 2
else:
    label = pos[1]
    label = label[0]
    
print('label=',label)
print('prob=',np.max(result))

label= 1
prob= 0.983986058554


# Save the whole thing

In [24]:
# import jieba
# import numpy as np

# class CutDebt:
    
#     def __init__(self, **model):
#         """
#         suggested parameters:
#         svc, logistic, lightgbm, jieba_path,tfidf
#         """
#         self._load_model(**model)
        
#     def _load_model(self,**model):
#         self.svc = model.get('svc')
#         self.logistic = model.get('logistic')
#         self.lightgbm = model.get('lightgbm')
#         self.tfidf = model.get('tfidf')
#         # load jieba
#         jieba_path = model.get('jieba_path')
#         if jieba_path is not None:
#             jieba.load_userdict(jieba_path)
        
        
#     def classify(self, sentence):
#         sentence = jieba.cut(sentence, cut_all = False)
#         sentence = ' '.join(sentence)
#         matrix = self.tfidf.transform([sentence])
#         result = np.vstack((self.svc.predict_proba(matrix),
#                             self.logistic.predict_proba(matrix),
#                             self.lightgbm.predict(matrix)))
#         max_pred = np.max(result, axis=0)
#         max_arg = np.argmax(max_pred)
#         threshold = 0.6
#         if np.max(max_pred)<threshold:
#             label = 2
#         else:
#             label = max_arg
#         return (label, np.max(max_pred))
     
        

In [25]:
%load_ext autoreload
%autoreload 2

In [26]:
from CutDebt_py import CutDebt
cutd = CutDebt(svc=clf, logistic=log_r, lightgbm=lgbm_model, tfidf=phrase_vectorizer, jieba_path='../WordCut/userdict.txt')

pickle.dump(cutd, open("../../savedModel/CutDebt/CutDebt.pickle", "wb"))

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.432 seconds.
Prefix dict has been built succesfully.
